# 1. Service Account untuk Filebeat
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-sa
  namespace: perpustakaan-ns
---
# 2. Cluster Role: Izin untuk membaca log dan metadata K8s
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-role
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources:
  - replicasets
  verbs: ["get", "watch", "list"]
---
# 3. Cluster Role Binding: Mengikat Role ke Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-role-binding
subjects:
- kind: ServiceAccount
  name: filebeat-sa
  namespace: perpustakaan-ns
roleRef:
  kind: ClusterRole
  name: filebeat-role
  apiGroup: rbac.authorization.k8s.io