## YAML Template.
---
server:
    port: 9091
    
spring:
    application:
        name: API_GATEWAY
    cloud:
        gateway:
                server:
                    webmvc:         
                        routes:
                        - id: BUKU
                          uri: lb://BUKU
                          predicates: 
                            - Path=api/buku/**
                        - id: ANGGOTA
                          uri: lb://ANGGOTA
                          predicates: 
                            - Path=api/anggota/**
                        - id: PEMINJAMAN
                          uri: lb://PEMINJAMAN
                          predicates: 
                            - Path=api/peminjaman/**
                        - id: PENGEMBALIAN
                          uri: lb://PENGEMBALIAN-SERVICE
                          predicates: 
                            - Path=api/pengembalian/**
eureka:
    client:
        service-url:
            # GANTI HOSTNAME di file YML/Properties service API_GATEWAY
            defaultZone: http://eureka-server:8761/eureka/ 
    instance: 
        # Tambahkan hostname di sini agar Gateway terdaftar dengan nama yang benar di Eureka
        hostname: api_gateway 
